apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp-deployment
    type: application
spec:
  selector:
    matchLabels:
      app: myapp-deployment
  replicas: 2
  template:
    metadata:
      name: myapp-deployment
      labels:
        app: myapp-deployment
    spec:
      containers:
        - name: nginx
          image: nginx
      
