apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp-deployment
    type: application
spec:
  selector:
    matchLabels:
      app: myapp-deployment
  replicas: 2
  restartPolicy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  livenessProbe:
    httpGet:
      path: /my
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  template:
    metadata:
      name: myapp-deployment
      labels:
        app: myapp-deployment
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              memory: "256Mi"
              cpu: 2
            limits:
              memory: "256Mi"
              cpu: 2
        
