apiVersion: v1
kind: pod
metadata:
  name: multipod-app
  labels: 
    name: multipod-app
spec:
  containers:
    - name: nginx-app1
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "250m"
    - name: nginx-app2
      image: nginx