apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: replica
  labels: 
    app: replica
    type: test
spec: 
  template: 
    metadata: 
      name: replica
      labels: 
        app: replica
        type: test
    spec: 
      containers: 
        - name: nginx-controller
          image: nginx
  replicas: 3
  selector: 
    matchLabels:
      type: test