---
apiVersion: v1
kind: Namespace
metadata:
  name: dvl1987

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: dvl1987
data:
  TIME_FREQ: "10"
  
---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  containers:
    - name: time-check
      image: busybox
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      command: ["/bin/sh"]
      args: ["-c", "while true; do date; sleep $(TIME_FREQ); done > /opt/time/time-check.log"]
      volumeMounts:
        - name:  time-check
          mountPath: /opt/time/
  volumes:
    - name:  time-check
      emptyDir: {}

        